# pipeline.yml
---
version: '1'
stages:
  - name: Test AWS S3
    inputs:
      - type: git
        branch: main
    triggers:
      - type: manual
    jobs:
      - name: List S3 Buckets
        type: builder
        build_type: shell
        script: |
          #!/bin/bash
          set -e

          echo "=== Installing AWS CLI ==="
          if ! command -v aws &> /dev/null; then
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip -q awscliv2.zip
            sudo ./aws/install
          fi

          echo "=== Checking AWS CLI Version ==="
          aws --version

          echo "=== Listing S3 Buckets ==="
          aws s3 ls
