apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: lambda-from-s3-zip-pipeline
spec:
  workspaces:
    - name: ws
  params:
    # ---- REGION & LAMBDA DETAILS ----
    - name: AWS_DEFAULT_REGION
      default: ca-central-1
    - name: FUNCTION_NAME
      default: rajusin4
    - name: ROLE_NAME
      default: lambda-basic-exec
    - name: RUNTIME
      default: python3.11
    - name: HANDLER
      default: handler.lambda_handler
    - name: SOURCE_BUCKET
      default: amzn-cicd-bucket
    - name: SOURCE_KEY
      default: lambda.zip
    # ---- "HARDCODED" AWS CREDS (DEMO ONLY) ----
    - name: AWS_ACCESS_KEY_ID
      default: "AKIA5FTZEWWEST5T6JO2"        # ⚠️ demo only
    - name: AWS_SECRET_ACCESS_KEY
      default: "E7kjBdtoc2NFguEgbzDOG3zxGsvSmJuzxW6fOais"        # ⚠️ demo only
    - name: AWS_SESSION_TOKEN
      default: ""                              # optional if using STS/SSO

  tasks:
    - name: fetch-and-deploy
      params:
        - name: AWS_DEFAULT_REGION
          value: $(params.AWS_DEFAULT_REGION)
        - name: FUNCTION_NAME
          value: $(params.FUNCTION_NAME)
        - name: ROLE_NAME
          value: $(params.ROLE_NAME)
        - name: RUNTIME
          value: $(params.RUNTIME)
        - name: HANDLER
          value: $(params.HANDLER)
        - name: SOURCE_BUCKET
          value: $(params.SOURCE_BUCKET)
        - name: SOURCE_KEY
          value: $(params.SOURCE_KEY)
        - name: AWS_ACCESS_KEY_ID
          value: $(params.AWS_ACCESS_KEY_ID)
        - name: AWS_SECRET_ACCESS_KEY
          value: $(params.AWS_SECRET_ACCESS_KEY)
        - name: AWS_SESSION_TOKEN
          value: $(params.AWS_SESSION_TOKEN)
      taskSpec:
        params:
          - name: AWS_DEFAULT_REGION
          - name: FUNCTION_NAME
          - name: ROLE_NAME
          - name: RUNTIME
          - name: HANDLER
          - name: SOURCE_BUCKET
          - name: SOURCE_KEY
          - name: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
          - name: AWS_SESSION_TOKEN
        workspaces:
          - name: ws
        steps:
          - name: install-awscli-and-deploy
            image: ubuntu:22.04
            workingDir: /workspace/ws
            env:
              - name: AWS_REGION
                value: $(params.AWS_DEFAULT_REGION)
              - name: AWS_DEFAULT_REGION
                value: $(params.AWS_DEFAULT_REGION)
              - name: AWS_ACCESS_KEY_ID
                value: $(params.AWS_ACCESS_KEY_ID)
              - name: AWS_SECRET_ACCESS_KEY
                value: $(params.AWS_SECRET_ACCESS_KEY)
              - name: AWS_SESSION_TOKEN
                value: $(params.AWS_SESSION_TOKEN)
            script: |
              #!/usr/bin/env bash
              set -euo pipefail

              REGION="${AWS_REGION:-${AWS_DEFAULT_REGION:-}}"
              : "${REGION:?AWS region is empty}"

              FUNCTION_NAME="$(params.FUNCTION_NAME)"
              ROLE_NAME="$(params.ROLE_NAME)"
              RUNTIME="$(params.RUNTIME)"
              HANDLER="$(params.HANDLER)"
              SRC_BUCKET="$(params.SOURCE_BUCKET)"
              SRC_KEY="$(params.SOURCE_KEY)"

              echo "== Install prerequisites =="
              apt-get update -y >/dev/null
              apt-get install -y unzip curl >/dev/null

              echo "== Install AWS CLI v2 =="
              curl -fsSL "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"
              unzip -q /tmp/awscliv2.zip -d /tmp
              /tmp/aws/install --bin-dir /usr/local/bin --update
              aws --version

              echo "== Configure AWS CLI with inline creds =="
              mkdir -p ~/.aws
              {
                echo "[default]"
                echo "aws_access_key_id=${AWS_ACCESS_KEY_ID}"
                echo "aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}"
                if [ -n "${AWS_SESSION_TOKEN:-}" ]; then
                  echo "aws_session_token=${AWS_SESSION_TOKEN}"
                fi
              } > ~/.aws/credentials

              {
                echo "[default]"
                echo "region=${REGION}"
                echo "output=json"
              } > ~/.aws/config

              echo "== Sanity check credentials/region =="
              aws sts get-caller-identity --region "$REGION" >/dev/null

              echo "== Download Lambda ZIP from S3 =="
              mkdir -p artifacts
              aws s3 cp "s3://${SRC_BUCKET}/${SRC_KEY}" "artifacts/lambda.zip" --region "$REGION"
              test -s artifacts/lambda.zip || { echo "Downloaded ZIP missing/empty"; exit 1; }

              echo "== Ensure IAM role exists =="
              if ! aws iam get-role --role-name "$ROLE_NAME" --region "$REGION" >/dev/null 2>&1; then
                cat > trust-policy.json <<'EOF'
              {
                "Version": "2012-10-17",
                "Statement": [
                  { "Effect": "Allow", "Principal": { "Service": "lambda.amazonaws.com" }, "Action": "sts:AssumeRole" }
                ]
              }
              EOF
                aws iam create-role --role-name "$ROLE_NAME" \
                  --assume-role-policy-document file://trust-policy.json \
                  --region "$REGION" >/dev/null
                aws iam attach-role-policy --role-name "$ROLE_NAME" \
                  --policy-arn arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole \
                  --region "$REGION" >/dev/null
                echo "Waiting for IAM role propagation..."
                sleep 15
              fi

              ACCOUNT_ID="$(aws sts get-caller-identity --query Account --output text --region "$REGION")"
              ROLE_ARN="arn:aws:iam::${ACCOUNT_ID}:role/${ROLE_NAME}"

              echo "== Create or Update Lambda from local ZIP =="
              if aws lambda get-function --function-name "$FUNCTION_NAME" --region "$REGION" >/dev/null 2>&1; then
                aws lambda update-function-code \
                  --function-name "$FUNCTION_NAME" \
                  --zip-file "fileb://$(pwd)/artifacts/lambda.zip" \
                  --region "$REGION" >/dev/null
              else
                aws lambda create-function \
                  --function-name "$FUNCTION_NAME" \
                  --runtime "$RUNTIME" \
                  --handler "$HANDLER" \
                  --role "$ROLE_ARN" \
                  --zip-file "fileb://$(pwd)/artifacts/lambda.zip" \
                  --timeout 10 \
                  --memory-size 128 \
                  --architectures x86_64 \
                  --region "$REGION" >/dev/null
              fi

              echo "== Lambda Status =="
              aws lambda get-function --function-name "$FUNCTION_NAME" --region "$REGION" \
                --query 'Configuration.{Name:FunctionName,Runtime:Runtime,LastModified:LastModified,Role:Role}' \
                --output table
      workspaces:
        - name: ws
