apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: lambda-from-s3-zip-pipeline
spec:
  workspaces:
    - name: ws
  params:
    - name: AWS_DEFAULT_REGION
      default: ca-central-1
    - name: FUNCTION_NAME
      default: rajusin4
    - name: ROLE_NAME
      default: lambda-basic-exec
    - name: RUNTIME
      default: python3.11
    - name: HANDLER
      default: handler.lambda_handler
    - name: SOURCE_BUCKET
      default: amzn-cicd-bucket
    - name: SOURCE_KEY
      default: lambda.zip
    - name: AWS_REGION
      default: ca-central-1

  tasks:
    - name: fetch-and-deploy
      params:
        - name: AWS_DEFAULT_REGION
          value: $(params.AWS_DEFAULT_REGION)
        - name: FUNCTION_NAME
          value: $(params.FUNCTION_NAME)
        - name: ROLE_NAME
          value: $(params.ROLE_NAME)
        - name: RUNTIME
          value: $(params.RUNTIME)
        - name: HANDLER
          value: $(params.HANDLER)
        - name: SOURCE_BUCKET
          value: $(params.SOURCE_BUCKET)
        - name: SOURCE_KEY
          value: $(params.SOURCE_KEY)
      taskSpec:
        params:
          - name: AWS_DEFAULT_REGION
          - name: FUNCTION_NAME
          - name: ROLE_NAME
          - name: RUNTIME
          - name: HANDLER
          - name: SOURCE_BUCKET
          - name: SOURCE_KEY
        workspaces:
          - name: ws
        steps:
          - name: verify-aws-env
            image: ubuntu:22.04
            env:
              - name: AWS_REGION
                value: $(params.AWS_DEFAULT_REGION)
              - name: AWS_DEFAULT_REGION
                value: $(params.AWS_DEFAULT_REGION)
              # Correctly reference Secure Environment Properties
              - name: AWS_ACCESS_KEY_ID
                value: $(AWS_ACCESS_KEY_ID)  # Ensure this is injected correctly
              - name: AWS_SECRET_ACCESS_KEY
                value: $(AWS_SECRET_ACCESS_KEY)  # Ensure this is injected correctly
              - name: AWS_SESSION_TOKEN
                value: $(AWS_SESSION_TOKEN)   # Optional if using session tokens
            script: |
              #!/usr/bin/env bash
              set -euo pipefail
              echo "AWS_REGION: ${AWS_REGION:-<empty>}"
              echo "AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION:-<empty>}"
              echo -n "AWS_ACCESS_KEY_ID: "; echo "${AWS_ACCESS_KEY_ID:-<empty>}"
              echo -n "AWS_SECRET_ACCESS_KEY: "; echo "${AWS_SECRET_ACCESS_KEY:-<empty>}"
              echo -n "AWS_SESSION_TOKEN: "; echo "${AWS_SESSION_TOKEN:-<empty>}"
              if [ -z "${AWS_ACCESS_KEY_ID:-}" ] || [ -z "${AWS_SECRET_ACCESS_KEY:-}" ]; then
                echo "❌ Missing AWS creds in env. Set them as Secure Environment properties on the pipeline."
                exit 1
              fi

      workspaces:
        - name: ws
