apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: simple-pipeline
spec:
  params:
    - name: MESSAGE
      type: string
      description: The message to echo
  tasks:
    - name: echo-task
      taskRef:
        name: echo-message-task
      params:
        - name: MESSAGE
          value: "$(params.MESSAGE)"
