apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: simple-pipelinerun
spec:
  pipelineRef:
    name: simple-pipeline
  params:
    - name: MESSAGE
      value: "Hello from Tekton on IBM Cloud!"
