apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: lambda-from-s3-zip-pipeline
spec:
  workspaces:
    - name: ws
  params:
    - name: AWS_DEFAULT_REGION
      default: ca-central-1
    - name: FUNCTION_NAME
      default: rajusin4
    - name: ROLE_NAME
      default: lambda-basic-exec
    - name: RUNTIME
      default: python3.11
    - name: HANDLER
      default: handler.lambda_handler
    - name: SOURCE_BUCKET
      default: amzn-cicd-bucket
    - name: SOURCE_KEY
      default: lambda.zip
    - name: AWS_REGION
      default: ca-central-1
    - name: AWS_ACCESS_KEY_ID
      default: "<AWS_ACCESS_KEY_ID>"
    - name: AWS_SECRET_ACCESS_KEY
      default: "<AWS_SECRET_ACCESS_KEY>"

  tasks:
    - name: fetch-and-deploy
      params:
        - name: AWS_DEFAULT_REGION
          value: $(params.AWS_DEFAULT_REGION)
        - name: FUNCTION_NAME
          value: $(params.FUNCTION_NAME)
        - name: ROLE_NAME
          value: $(params.ROLE_NAME)
        - name: RUNTIME
          value: $(params.RUNTIME)
        - name: HANDLER
          value: $(params.HANDLER)
        - name: SOURCE_BUCKET
          value: $(params.SOURCE_BUCKET)
        - name: SOURCE_KEY
          value: $(params.SOURCE_KEY)
        - name: AWS_ACCESS_KEY_ID
          value: $(params.AWS_ACCESS_KEY_ID)
        - name: AWS_SECRET_ACCESS_KEY
          value: $(params.AWS_SECRET_ACCESS_KEY)
      taskSpec:
        params:
          - name: AWS_DEFAULT_REGION
          - name: FUNCTION_NAME
          - name: ROLE_NAME
          - name: RUNTIME
          - name: HANDLER
          - name: SOURCE_BUCKET
          - name: SOURCE_KEY
          - name: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
        workspaces:
          - name: ws
        steps:
          - name: verify-aws-env
            image: ubuntu:22.04
            env:
              - name: AWS_ACCESS_KEY_ID
                value: $(params.AWS_ACCESS_KEY_ID)
              - name: AWS_SECRET_ACCESS_KEY
                value: $(params.AWS_SECRET_ACCESS_KEY)
              - name: AWS_SESSION_TOKEN
                value: $(params.AWS_SESSION_TOKEN)
            script: |
              #!/usr/bin/env bash
              set -euo pipefail
              echo "AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}"
              echo "AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}"
              echo "AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}"
              if [ -z "$AWS_ACCESS_KEY_ID" ] || [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
                echo "❌ Missing AWS creds in env."
                exit 1
              fi
