apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: lambda-from-s3-zip-pipeline
spec:
  workspaces:
    - name: ws
  params:
    - name: AWS_DEFAULT_REGION
      default: ca-central-1
    - name: FUNCTION_NAME
      default: rajusin4
    - name: ROLE_NAME
      default: lambda-basic-exec
    - name: RUNTIME
      default: python3.11
    - name: HANDLER
      default: handler.lambda_handler
    - name: SOURCE_BUCKET
      default: amzn-cicd-bucket
    - name: SOURCE_KEY
      default: lambda.zip
    #- name: AWS_ACCESS_KEY_ID
    #  default: "AKIA5FTZEWWEST5T6JO2"
    #- name: AWS_SECRET_ACCESS_KEY
    #  default: "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"
    - name: AWS_REGION
      default: ca-central-1
    # Optional: uncomment if you insist on hardcoding via params (demo only)
    # - name: AWS_ACCESS_KEY_ID
    #   default: "REPLACE_ME"
    # - name: AWS_SECRET_ACCESS_KEY
    #   default: "REPLACE_ME"
    # - name: AWS_SESSION_TOKEN
    #   default: ""

  tasks:
    - name: fetch-and-deploy
      params:
        - name: AWS_DEFAULT_REGION
          value: $(params.AWS_DEFAULT_REGION)
        - name: FUNCTION_NAME
          value: $(params.FUNCTION_NAME)
        - name: ROLE_NAME
          value: $(params.ROLE_NAME)
        - name: RUNTIME
          value: $(params.RUNTIME)
        - name: HANDLER
          value: $(params.HANDLER)
        - name: SOURCE_BUCKET
          value: $(params.SOURCE_BUCKET)
        - name: SOURCE_KEY
          value: $(params.SOURCE_KEY)
        # If using hardcoded params above, pass them here too.
      taskSpec:
        params:
          - name: AWS_DEFAULT_REGION
          - name: FUNCTION_NAME
          - name: ROLE_NAME
          - name: RUNTIME
          - name: HANDLER
          - name: SOURCE_BUCKET
          - name: SOURCE_KEY
        workspaces:
          - name: ws
        steps:

          # 0) Verify creds & region are injected (no secret printing)
          - name: verify-aws-env
            image: ubuntu:22.04
            env:
              - name: AWS_REGION
                value: $(params.AWS_DEFAULT_REGION)
              - name: AWS_DEFAULT_REGION
                value: $(params.AWS_DEFAULT_REGION)
              # 👇 map pipeline Environment properties into the container env
              - name: AWS_ACCESS_KEY_ID
                value: "$(AWS_ACCESS_KEY_ID)"
              - name: AWS_SECRET_ACCESS_KEY
                value: "$(AWS_SECRET_ACCESS_KEY)"
              - name: AWS_SESSION_TOKEN
                value: "$(AWS_SESSION_TOKEN)"   # safe if unset; we’ll handle it in script
              # If you used params for creds, also map them here:
              #- name: AWS_ACCESS_KEY_ID
              #  value: "AKIA5FTZEWWEST5T6JO2"
              #- name: AWS_SECRET_ACCESS_KEY
              #  value: "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"
              - name: AWS_REGION
                value: ca-central-1
              #- name: AWS_SESSION_TOKEN
              #  value: $(params.AWS_SESSION_TOKEN)
            script: |
              #!/usr/bin/env bash
              set -euo pipefail
              mask() {
                v="${1:-}"; if [ -z "$v" ]; then echo "<empty>"; else
                  printf "%s***%s (len %d)\n" "${v:0:2}" "${v: -2}" "${#v}"
                fi
              }
              echo "AWS_REGION: ${AWS_REGION:-<empty>}"
              echo "AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION:-<empty>}"
              echo -n "AWS_ACCESS_KEY_ID: "; "${AWS_ACCESS_KEY_ID:-}"
              echo -n "AWS_SECRET_ACCESS_KEY: "; "${AWS_SECRET_ACCESS_KEY:-}"
              echo -n "AWS_SESSION_TOKEN: "; "${AWS_SESSION_TOKEN:-}"
              if [ -z "${AWS_ACCESS_KEY_ID:-}" ] || [ -z "${AWS_SECRET_ACCESS_KEY:-}" ]; then
                echo "❌ Missing AWS creds in env. Set them as Secure Environment properties on the pipeline."
                exit 1
              fi

      workspaces:
        - name: ws
