apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: lambda-from-s3-zip-run
spec:
  pipelineRef:
    name: lambda-from-s3-zip-pipeline
  params:
    - name: AWS_DEFAULT_REGION
      value: ca-central-1
    - name: FUNCTION_NAME
      value: rajusin4-lambda
    - name: ROLE_NAME
      value: lambda-basic-exec
    - name: RUNTIME
      value: python3.11
    - name: HANDLER
      value: handler.lambda_handler
    - name: SOURCE_BUCKET
      value: amzn-cicd-bucket
    - name: SOURCE_KEY
      value: lambda.zip
  workspaces:
    - name: ws
      emptyDir: {}
