apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: echo-message-task
spec:
  params:
    - name: MESSAGE
      type: string
  steps:
    - name: echo
      image: ubuntu:22.04
      script: |
        #!/bin/bash
        echo "Message: $(params.MESSAGE)"
