apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: simple-pipeline-template
spec:
  params:
    - name: MESSAGE
      description: The message to echo
      default: "Hello from Tekton!"
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        name: $(tt.params.MESSAGE)-run
      spec:
        pipelineRef:
          name: simple-pipeline
        params:
          - name: MESSAGE
            value: $(tt.params.MESSAGE)
