apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: hello-ibmcloud-pipeline
spec:
  workspaces:
    - name: ws
  params:
    - name: MESSAGE
      description: "Message to print"
      default: "Hello from IBM Cloud Tekton!"
  tasks:
    - name: hello
      taskSpec:
        params:
          - name: MESSAGE
        steps:
          - name: print
            image: ubuntu:22.04
            script: |
              #!/usr/bin/env bash
              set -e
              echo "===================================="
              echo "✅ Running inside IBM Cloud Tekton"
              echo "✅ Message: $(params.MESSAGE)"
              echo "===================================="
