apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: hello-world-pipeline
spec:
  params:
    - name: MESSAGE
      description: Message to print
      default: "Hello, Tekton World!"
  workspaces:
    - name: ws
  tasks:
    - name: say-hello
      taskSpec:
        params:
          - name: MESSAGE
        steps:
          - name: print-message
            image: ubuntu:22.04
            script: |
              #!/usr/bin/env bash
              set -euo pipefail
              echo "✅ $(params.MESSAGE)"
