apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: hello-binding
spec:
  params:
    - name: message
      value: $(body.message)               # POST {"message":"Hi!"} to override
