# event-listener.yaml for hello world
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: hello-world-event-listener
spec:
  triggers:
    - name: hello-world-trigger
      bindings:
        - ref: hello-world-trigger-binding
      template:
        ref: hello-world-trigger-template
